MODEL:
  TYPE: vit
  NAME: ropim_finetune
  DROP_PATH_RATE: 0.1
  VIT:
    EMBED_DIM: 192
    DEPTH: 12
    NUM_HEADS: 3
    USE_APE: False
    USE_RPB: True
    USE_SHARED_RPB: False
    USE_MEAN_POOLING: True
DATA:
  IMG_SIZE: 224
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 5
  BASE_LR: 1e-2
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-7
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.7 
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: ropim_finetune__vit_tiny_imagenet100
