MODEL:
  TYPE: vit
  NAME: simsim_pretrain
  DROP_PATH_RATE: 0.1
  VIT:
    EMBED_DIM: 192
    PATCH_SIZE: 4 #16  (ADIO setting: 4)
    DEPTH: 12
    NUM_HEADS: 3
    USE_APE: False
    USE_RPB: False
    USE_SHARED_RPB: True
    USE_MEAN_POOLING: False
DATA:
  IMG_SIZE: 64 #224 (ADIO setting: 64)

TRAIN:
  EPOCHS: 800
  WARMUP_EPOCHS: 10
  BASE_LR: 1e-3
  WARMUP_LR: 5e-7
  WEIGHT_DECAY: 0.05
  LR_SCHEDULER:
    NAME: 'multistep'
    GAMMA: 0.1
    MULTISTEPS: [700,]
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: simmim_pretrain__vit_tiny__img224__800ep
