MODEL:
  TYPE: vit
  NAME: simsim_finetune
  DROP_PATH_RATE: 0.1
  VIT:
    EMBED_DIM: 192
    PATCH_SIZE: 4 # (Org: 16, ADIOS setting: 4)
    DEPTH: 12
    NUM_HEADS: 3
    USE_APE: False
    USE_RPB: True
    USE_SHARED_RPB: False
    USE_MEAN_POOLING: True
DATA:
  IMG_SIZE: 64 #(Org: 224, ADIOS setting: 64)

AUG:
  COLOR_JITTER: .4
  AUTO_AUGMENT: None #'rand-m9-mstd0.5-inc1'
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 5
  BASE_LR: 10e-3 # 1.25e-3
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-7
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.65
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: simmim_finetune__vit_base__img224__800ep
