MODEL:
  TYPE: vit
  NAME: ropim_finetune
  DROP_PATH_RATE: 0.1
  VIT:
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    USE_APE: False
    USE_RPB: True
    USE_SHARED_RPB: False
    USE_MEAN_POOLING: True
DATA:
  IMG_SIZE: 224
AUG:
  AUTO_AUGMENT: 'rand-m9-mstd0.5-inc1'
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 5
  BASE_LR: 5e-3 #8.0e-4  #1.25e-3 # 2.5e-3 #
  WARMUP_LR: 2.5e-7
  MIN_LR: 5.0e-6 #2.5e-7 #
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.75 # 0.8 . 0.65 
  OPTIMIZER:
    BETAS: (0.9, 0.999)
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: ropim_finetune__vit_base__img224
